working on dims

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -1,7 +1,18 @@
 #!/bin/bash
 
 dims() {
-	echo arg = $1		
+	if [ $# -ne "0" ] || [ $# -ne "1" ]
+	then
+		echo "Error" 1>&2
+		exit 1
+	elif [ $# = "1" ] && [ ! -r $1 ]
+	then
+		echo "Error" 1>&2
+		exit 1
+	else
+		cols=$(< "$1": wc -l)
+		
+	fi		 		
 }
 
 transpose() {
